INSERT INTO USER_KIND
VALUES(1,'Chủ nhà');
INSERT INTO USER_KIND
VALUES(2,'Môi giới');
INSERT INTO USER
VALUES(1,'ladjfa@gmail.com','Sophia','asldkf','021651',2);
INSERT INTO USER
VALUES(2,'ladjfa@gmail.com','Sophia','asldkf','021651',1);
INSERT INTO REAL_ESTATE_KIND
VALUES(1,'chung cư');
INSERT INTO TRADE_KIND
VALUES(1,'mua');
INSERT INTO ADDRESS
VALUES(1,'Số nhà 34','Đường Kha Vạn Cân', 'Phường 3','Quận Thủ Đức','Tp. Hồ Chí Minh');
INSERT INTO DETAILS
VALUES(2,3,3,'','','',32,'',665,'',32);
INSERT INTO BOOKING
VALUES(3,'','','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TRADE
VALUES(1,35000,'Đây là phần mô tả',1,3,2,1,1,1);

